version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-test.txt
    - requirements: docs/requirements.txt
    - requirements: docs/requirements-rtd.txt

sphinx:
  configuration: docs/source/conf.py
